conversation_style: 
  - "engaging"
  - "fast-paced"
  - "enthusiastic"
roles_person1: "main summarizer"
roles_person2: "questioner/clarifier"
dialogue_structure: 
  - "Introduction"
  - "Main Content Summary"
  - "Conclusion"
podcast_name: "PODCASTIFY"
podcast_tagline: "Your Personal Generative AI Podcast"
output_language: "English"
engagement_techniques: 
  - "rhetorical questions"
  - "anecdotes"
  - "analogies"
  - "humor"
creativity: 1
user_instructions: ""
max_num_chunks: 8 # maximum number of rounds of discussions in longform
min_chunk_size: 600 # minimum number of characters to generate a round of discussion in longform

text_to_speech:
  default_tts_model: "openai"
  output_directories:
    transcripts: "./data/transcripts"
    audio: "./data/audio"
  elevenlabs:
    default_voices:
      question: "Chris"
      answer: "Jessica"
    model: "eleven_multilingual_v2"
  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
    model: "tts-1-hd"
  edge:
    default_voices:
      question: "en-US-JennyNeural"
      answer: "en-US-EricNeural"
  gemini:
    default_voices:
      question: "en-US-Journey-D"
      answer: "en-US-Journey-O"
  geminimulti:
    default_voices:
      question: "R"
      answer: "S"
      model: "en-US-Studio-MultiSpeaker"
  gemini_flash_tts:
    default_voices:
      question: "it-IT-Standard-A"
      answer: "it-IT-Standard-B"
    model: "gemini-2.5-flash-preview-tts"
    modalities:
      - "audio"
    audioConfig:
      format: "pcm16"
      speakingRate: 1.0
    generationConfig:
      temperature: 1.0
      topP: 0.9
      topK: 40
      candidateCount: 1
    thinkingConfig:
      budgetTokens: 0
    requestOptions:
      timeout: 120
    responseMimeType: "audio/mp3"
  audio_format: "mp3"
  temp_audio_dir: "data/audio/tmp/"
  ending_message: "See You Next Time!"
